name: crew_app
description: "Movermate Crew App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  skeletonizer: ^1.4.2
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  map_launcher: ^3.5.0

  # require higher sdk
  webview_flutter: ^4.8.0
  dotted_line: ^3.2.2
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  cunning_document_scanner: ^1.2.3
  cached_network_image: ^3.4.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_tabler_icons: ^1.36.0
  flutter_local_notifications: ^17.2.2
  get_storage: ^2.1.1
  logger: ^2.4.0
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  timeago: ^3.7.0
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  infinite_scroll_pagination:
    path: plugins/infinite_scroll_pagination
  custom_sliding_segmented_control: ^1.8.3
  path_provider: ^2.1.4
  path: ^1.9.0
  dropdown_button2: ^2.3.9
  sliding_up_panel: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
 

  # require higher sdk
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.7.0
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
     - assets/images/
     - assets/svgs/
     - assets/fonts/
     - assets/colors/
     - assets/lotties/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Thin.ttf
           weight: 100
         - asset: assets/fonts/Poppins-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/Poppins-ExtraBold.ttf
           weight: 800
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml
  integrations:
    flutter_svg: true

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
